# Generated by Django 2.1.7 on 2019-06-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190613_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ürün fotoğrafı ekleyin'),
        ),
    ]
