# Generated by Django 2.1.7 on 2019-06-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
    ]
